stages:
  - test

pytest:
  stage: test
  image: python:3.8
  script:
    - pip install -r requirements.txt
    - python -m playwright install chromium
    - python -m pytest --clean-alluredir
  after_script:
    -  allure serve allure-results
  artifacts:
    when: always
    paths:
      - allure-results\*

  only:
    - master
