stages:
  - test

pytest:
  stage: test
  image: python:3.8
  script:
    - pip install -r requirements.txt
    - python -m playwright install chromium
    - pytest --junitxml=junit.xml
  artifacts:
    reports:
      junit: junit.xml

pages:
  stage: test
  image: python:3.8
  script:
    - apt-get update && apt-get install -y allure
    - allure generate --clean -o allure-report ./allure-results
  artifacts:
    paths:
      - allure-report/
  only:
    - master
